name: Deploy to VDS

on:
  push:
    branches:
      - main # main dalına (branch) kod gönderildiğinde çalışır

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Sunucuya bağlan ve kodu güncelle
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.PORT }}
          script: |
            cd /var/www/gencsosyalweb
            git pull origin main
            docker compose pull
            docker compose up -d --build
